sonar.projectKey=Shaunak-ondare_Ansible-devsecops-tf
sonar.organization=shaunak-ondare

# Since we are using the dotnet-sonarscanner, it will automatically 
# detect the source files from your .csproj.
sonar.sources=DotNetApp

# Encoding of the source code.
sonar.sourceEncoding=UTF-8
