---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Install gnupg and curl
  apt:
    name: "{{ item }}"
    state: present
  loop: [gnupg, curl]

- name: Add MongoDB GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-7.0.asc
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
    state: present
    filename: mongodb-org-7.0

- name: Update apt cache for MongoDB
  apt:
    update_cache: yes

- name: Install MongoDB (Official)
  apt:
    name: mongodb-org
    state: present

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Ensure MongoDB is running
  service:
    name: mongod
    state: started
    enabled: yes
