---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present

- name: Install MongoDB
  apt:
    name: mongodb
    state: present

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Ensure MongoDB is running
  service:
    name: mongodb
    state: started
    enabled: yes
