- name: Install IIS Web Server
  ansible.windows.win_feature:
    name: Web-Server
    state: present
    include_management_tools: yes

- name: Create directory for .NET App
  ansible.windows.win_file:
    path: C:\inetpub\wwwroot\DotNetApp
    state: directory

- name: Copy .NET Published files
  ansible.windows.win_copy:
    src: app_dist/
    dest: C:\inetpub\wwwroot\DotNetApp\

- name: Ensure temp directory exists
  ansible.windows.win_file:
    path: C:\temp
    state: directory

- name: Download .NET 8.0 Hosting Bundle
  ansible.windows.win_get_url:
    url: https://aka.ms/dotnet/8.0/dotnet-hosting-win.exe
    dest: C:\temp\dotnet-hosting-8.0.0-win-x64.exe

- name: Install .NET 8.0 Hosting Bundle
  ansible.windows.win_package:
    path: C:\temp\dotnet-hosting-8.0.0-win-x64.exe
    arguments: /install /quiet /norestart
    state: present
    expected_return_code: [0, 1641, 3010]

- name: Create or Update IIS App Pool
  community.windows.win_iis_webapppool:
    name: "DotNetAppPool"
    state: started
    managed_pipeline_mode: Integrated
    managed_runtime_version: ""

- name: Remove Default Web Site
  community.windows.win_iis_website:
    name: "Default Web Site"
    state: absent

- name: Create or Update IIS Site
  community.windows.win_iis_website:
    name: "DotNetApp"
    state: started
    port: 80
    physical_path: C:\inetpub\wwwroot\DotNetApp
    application_pool: "DotNetAppPool"

- name: Restart IIS to apply Hosting Bundle
  ansible.windows.win_shell: iisreset
